In [14]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('database.sqlite')
c = conn.cursor()

In [24]:
c.execute("""select * from matches where Season = 2011""")
df_matches = pd.DataFrame(c.fetchall())
df_matches.columns = [x[0] for x in c.description]
df_matches.head()

   Match_ID Div  Season        Date   HomeTeam       AwayTeam  FTHG  FTAG FTR
0      1092  D1    2011  2012-03-31   Nurnberg  Bayern Munich     0     1   A
1      1093  D1    2011  2011-12-11  Stuttgart  Bayern Munich     1     2   A
2      1094  D1    2011  2011-08-13  Wolfsburg  Bayern Munich     0     1   A
3      1095  D1    2011  2011-11-27      Mainz  Bayern Munich     3     2   H
4      1096  D1    2011  2012-02-18   Freiburg  Bayern Munich     0     0   D

In [68]:
df_dummy = df_matches[0:10].copy()

In [69]:
df_dummy

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D
5,1097,D1,2011,2012-01-20,M'gladbach,Bayern Munich,3,1,H
6,1098,D1,2011,2012-02-04,Hamburg,Bayern Munich,1,1,D
7,1099,D1,2011,2012-04-21,Werder Bremen,Bayern Munich,1,2,A
8,1100,D1,2011,2011-09-18,Schalke 04,Bayern Munich,0,2,A
9,1101,D1,2011,2011-10-23,Hannover,Bayern Munich,2,1,H

In [19]:
c.execute("""select * from teams""")
df_teams = pd.DataFrame(c.fetchall())
df_teams.columns = [x[0] for x in c.description]
df_teams.head()

,Season,TeamName,KaderHome,AvgAgeHome,ForeignPlayersHome,OverallMarketValueHome,AvgMarketValueHome,StadiumCapacity
0,2017,Bayern Munich,27,26,15,597950000,22150000,75000
1,2017,Dortmund,33,25,18,416730000,12630000,81359
2,2017,Leverkusen,31,24,15,222600000,7180000,30210
3,2017,RB Leipzig,30,23,15,180130000,6000000,42959
4,2017,Schalke 04,29,24,17,179550000,6190000,62271

In [20]:
c.execute("""select * from unique_teams""")
df_unique_teams = pd.DataFrame(c.fetchall())
df_unique_teams.columns = [x[0] for x in c.description]
df_unique_teams.head()

        TeamName  Unique_Team_ID
0  Bayern Munich               1
1       Dortmund               2
2     Leverkusen               3
3     RB Leipzig               4
4     Schalke 04               5

In [21]:
c.execute("""select * from teams_in_matches""")
df_teams_in_matches = pd.DataFrame(c.fetchall())
df_teams_in_matches.columns = [x[0] for x in c.description]
df_teams_in_matches.head()

   Match_ID  Unique_Team_ID
0         1              26
1         1              46
2         2              26
3         2              42
4         3              26

In [28]:
c.execute("""select * from Flatview""")
df_flatview = pd.DataFrame(c.fetchall())
df_flatview.columns = [x[0] for x in c.description]
df_flatview.head()

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,AvgAgeHome,...,ForeignPlayersHome,ForeignplayersAways,KaderHome,KaderAway,StadiumCapacity,StadiumCapacityAway,AvgMarketValueHome,MarketValueAway,OverallMarketValueHome,OverallMarketValueAway
0,1,D2,2009,2010-04-04,Oberhausen,Kaiserslautern,2,1,H,25,...,8,13,29,32,47728,47728,305000,747000,8850000,23900000
1,2,D2,2009,2009-11-01,Munich 1860,Kaiserslautern,0,1,A,24,...,18,13,33,32,47728,47728,658000,747000,21700000,23900000
2,3,D2,2009,2009-10-04,Frankfurt FSV,Kaiserslautern,1,1,D,26,...,20,13,34,32,47728,47728,385000,747000,13100000,23900000
3,4,D2,2009,2010-02-21,Frankfurt FSV,Karlsruhe,2,1,H,26,...,20,9,34,37,47728,47728,385000,570000,13100000,21100000
4,5,D2,2009,2009-12-06,Ahlen,Karlsruhe,1,3,A,25,...,14,9,37,37,47728,47728,349000,570000,12930000,21100000

In [29]:
df_flatview.columns

Index(['Match_ID', 'Div', 'Season', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG',
       'FTAG', 'FTR', 'AvgAgeHome', 'AvgAgeAway', 'ForeignPlayersHome',
       'ForeignplayersAways', 'KaderHome', 'KaderAway', 'StadiumCapacity',
       'StadiumCapacityAway', 'AvgMarketValueHome', 'MarketValueAway',
       'OverallMarketValueHome', 'OverallMarketValueAway'],
      dtype='object')

In [30]:
c.execute("""select * from Flatview_advanced""")
df_flatview = pd.DataFrame(c.fetchall())
df_flatview.columns = [x[0] for x in c.description]
df_flatview.head()

,Match_ID,Unique_Team_ID,Unique_Team,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,KaderHome,AvgAgeHome,ForeignPlayersHome,OverallMarketValueHome,AvgMarketValueHome,StadiumCapacity
0,5772,1,Bayern Munich,D1,2005,2005-08-05,Bayern Munich,M'gladbach,3,0,H,25,27,14,171500000,6860000,75000
1,5378,1,Bayern Munich,D1,2005,2005-08-13,Leverkusen,Bayern Munich,2,5,A,25,27,14,171500000,6860000,75000
2,5693,1,Bayern Munich,D1,2005,2005-08-27,Bayern Munich,Hertha,3,0,H,25,27,14,171500000,6860000,75000
3,5386,1,Bayern Munich,D1,2005,2005-09-10,Nurnberg,Bayern Munich,1,2,A,25,27,14,171500000,6860000,75000
4,5661,1,Bayern Munich,D1,2005,2005-09-17,Bayern Munich,Hannover,1,0,H,25,27,14,171500000,6860000,75000

In [31]:
#we need MongoDB documents with:
# 1. Team name
# 2. Total number of goals scored by team during in 2011
# 3. Total number of wins the team earned during in 2011
# 4. histogram visualization of team's wins and losses in 2011
# 5. Team's win percentage on days where it was raining during games in 2011

In [35]:
import requests
BERLIN_LATITUDE=52.5065133
BERLIN_LONGITUDE=13.144549
with open('darksky_api_key') as f: DARKSKY_API_KEY=f.read().strip()
DARKSKY_BASE_URL=f'https://api.darksky.net/forecast/{DARKSKY_API_KEY}/{BERLIN_LATITUDE},{BERLIN_LONGITUDE},'

In [36]:
import datetime
def get_api_timestamp_from_date(ymd_string):
    year,month,day=[int(number_string) for number_string in ymd_string.split('-')]
    return datetime.datetime(year,month,day,12,0,0).isoformat()

In [38]:
get_api_timestamp_from_date('2011-05-20')

'2011-05-20T12:00:00'

In [41]:
def get_weather_data_given_date(ymd_string):
    return requests.get(DARKSKY_BASE_URL+get_api_timestamp_from_date(ymd_string)).json()

In [43]:
get_weather_data_given_date("2019-05-19")

{'latitude': 52.5065133,
 'longitude': 13.144549,
 'timezone': 'Europe/Berlin',
 'currently': {'time': 1558260000,
  'summary': 'Clear',
  'icon': 'clear-day',
  'precipIntensity': 0,
  'precipProbability': 0,
  'temperature': 74.81,
  'apparentTemperature': 74.81,
  'dewPoint': 49.36,
  'humidity': 0.41,
  'pressure': 1005.75,
  'windSpeed': 11.7,
  'windGust': 14.23,
  'windBearing': 97,
  'cloudCover': 0.19,
  'uvIndex': 6,
  'visibility': 6.3,
  'ozone': 342.63},
 'hourly': {'summary': 'Mostly cloudy starting overnight, continuing until morning.',
  'icon': 'partly-cloudy-day',
  'data': [{'time': 1558216800,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 56.57,
    'apparentTemperature': 56.57,
    'dewPoint': 50,
    'humidity': 0.79,
    'pressure': 1007.56,
    'windSpeed': 0.79,
    'windGust': 3.35,
    'windBearing': 116,
    'cloudCover': 0.07,
    'uvIndex': 0,
    'visibility': 6.22,
    'ozone': 345.96},
   {'time': 1558220400,
    'summary': 'Clear',
    'icon': 'clear-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 56.55,
    'apparentTemperature': 56.55,
    'dewPoint': 48.73,
    'humidity': 0.75,
    'pressure': 1007.46,
    'windSpeed': 3.26,
    'windGust': 3.26,
    'windBearing': 66,
    'cloudCover': 0.13,
    'uvIndex': 0,
    'visibility': 6.21,
    'ozone': 345.21},
   {'time': 1558224000,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 53.6,
    'apparentTemperature': 53.6,
    'dewPoint': 49.19,
    'humidity': 0.85,
    'pressure': 1007.17,
    'windSpeed': 1.47,
    'windGust': 3.22,
    'windBearing': 24,
    'cloudCover': 0.25,
    'uvIndex': 0,
    'visibility': 6.22,
    'ozone': 344.15},
   {'time': 1558227600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 52.15,
    'apparentTemperature': 52.15,
    'dewPoint': 48.04,
    'humidity': 0.86,
    'pressure': 1007,
    'windSpeed': 4.95,
    'windGust': 4.95,
    'windBearing': 42,
    'cloudCover': 0.5,
    'uvIndex': 0,
    'visibility': 6.22,
    'ozone': 343.55},
   {'time': 1558231200,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 53.23,
    'apparentTemperature': 53.23,
    'dewPoint': 47.53,
    'humidity': 0.81,
    'pressure': 1006.9,
    'windSpeed': 4.42,
    'windGust': 4.42,
    'windBearing': 69,
    'cloudCover': 0.8,
    'uvIndex': 0,
    'visibility': 6.22,
    'ozone': 341.09},
   {'time': 1558234800,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 53.41,
    'apparentTemperature': 53.41,
    'dewPoint': 48.21,
    'humidity': 0.82,
    'pressure': 1006.83,
    'windSpeed': 4.08,
    'windGust': 4.94,
    'windBearing': 63,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 6.22,
    'ozone': 339.37},
   {'time': 1558238400,
    'summary': 'Overcast',
    'icon': 'cloudy',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 52.85,
    'apparentTemperature': 52.85,
    'dewPoint': 48.26,
    'humidity': 0.84,
    'pressure': 1006.76,
    'windSpeed': 4.04,
    'windGust': 6.26,
    'windBearing': 102,
    'cloudCover': 1,
    'uvIndex': 0,
    'visibility': 6.21,
    'ozone': 339.15},
   {'time': 1558242000,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 57.5,
    'apparentTemperature': 57.5,
    'dewPoint': 50.08,
    'humidity': 0.76,
    'pressure': 1006.73,
    'windSpeed': 3.32,
    'windGust': 7.9,
    'windBearing': 69,
    'cloudCover': 0.91,
    'uvIndex': 0,
    'visibility': 6.21,
    'ozone': 339.68},
   {'time': 1558245600,
    'summary': 'Mostly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 61.97,
    'apparentTemperature': 61.97,
    'dewPoint': 50.77,
    'humidity': 0.67,
    'pressure': 1006.66,
    'windSpeed': 5.66,
    'windGust': 9.15,
    'windBearing': 78,
    'cloudCover': 0.76,
    'uvIndex': 1,
    'visibility': 6.22,
    'ozone': 343.62},
   {'time': 1558249200,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 66.35,
    'apparentTemperature': 66.35,
    'dewPoint': 50.77,
    'humidity': 0.57,
    'pressure': 1006.5,
    'windSpeed': 5.56,
    'windGust': 10.93,
    'windBearing': 106,
    'cloudCover': 0.51,
    'uvIndex': 2,
    'visibility': 6.21,
    'ozone': 343.83},
   {'time': 1558252800,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 69.7,
    'apparentTemperature': 69.7,
    'dewPoint': 50.74,
    'humidity': 0.51,
    'pressure': 1006.29,
    'windSpeed': 7.87,
    'windGust': 12.75,
    'windBearing': 100,
    'cloudCover': 0.21,
    'uvIndex': 4,
    'visibility': 6.2,
    'ozone': 343.59},
   {'time': 1558256400,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 73.15,
    'apparentTemperature': 73.15,
    'dewPoint': 49.49,
    'humidity': 0.43,
    'pressure': 1006.03,
    'windSpeed': 13.23,
    'windGust': 13.99,
    'windBearing': 90,
    'cloudCover': 0.19,
    'uvIndex': 5,
    'visibility': 6.22,
    'ozone': 343.17},
   {'time': 1558260000,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 74.81,
    'apparentTemperature': 74.81,
    'dewPoint': 49.36,
    'humidity': 0.41,
    'pressure': 1005.75,
    'windSpeed': 11.7,
    'windGust': 14.23,
    'windBearing': 97,
    'cloudCover': 0.19,
    'uvIndex': 6,
    'visibility': 6.3,
    'ozone': 342.63},
   {'time': 1558263600,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 76.02,
    'apparentTemperature': 76.02,
    'dewPoint': 50.38,
    'humidity': 0.41,
    'pressure': 1005.44,
    'windSpeed': 11.25,
    'windGust': 13.9,
    'windBearing': 111,
    'cloudCover': 0.19,
    'uvIndex': 6,
    'visibility': 6.41,
    'ozone': 341.88},
   {'time': 1558267200,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 76.77,
    'apparentTemperature': 76.77,
    'dewPoint': 49.98,
    'humidity': 0.39,
    'pressure': 1005.02,
    'windSpeed': 12.99,
    'windGust': 13.33,
    'windBearing': 94,
    'cloudCover': 0.13,
    'uvIndex': 6,
    'visibility': 6.47,
    'ozone': 341.4},
   {'time': 1558270800,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 77.06,
    'apparentTemperature': 77.06,
    'dewPoint': 50.74,
    'humidity': 0.4,
    'pressure': 1004.76,
    'windSpeed': 11.58,
    'windGust': 11.98,
    'windBearing': 81,
    'cloudCover': 0.19,
    'uvIndex': 5,
    'visibility': 6.2,
    'ozone': 342.32},
   {'time': 1558274400,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0,
    'precipProbability': 0,
    'temperature': 75.99,
    'apparentTemperature': 75.99,
    'dewPoint': 52.7,
    'humidity': 0.44,
    'pressure': 1004.4,
    'windSpeed': 12.08,
    'windGust': 12.08,
    'windBearing': 73,
    'cloudCover': 0.19,
    'uvIndex': 4,
    'visibility': 6.2,
    'ozone': 342.86},
   {'time': 1558278000,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0.0003,
    'precipProbability': 0.01,
    'precipType': 'rain',
    'temperature': 71.26,
    'apparentTemperature': 71.26,
    'dewPoint': 54.72,
    'humidity': 0.56,
    'pressure': 1004.12,
    'windSpeed': 10.44,
    'windGust': 24.49,
    'windBearing': 49,
    'cloudCover': 0.44,
    'uvIndex': 2,
    'visibility': 6.27,
    'ozone': 343.41},
   {'time': 1558281600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-day',
    'precipIntensity': 0.0014,
    'precipProbability': 0.03,
    'precipType': 'rain',
    'temperature': 71.55,
    'apparentTemperature': 71.55,
    'dewPoint': 56.92,
    'humidity': 0.6,
    'pressure': 1003.97,
    'windSpeed': 9.01,
    'windGust': 11.04,
    'windBearing': 49,
    'cloudCover': 0.44,
    'uvIndex': 1,
    'visibility': 6.47,
    'ozone': 344.05},
   {'time': 1558285200,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0.0051,
    'precipProbability': 0.03,
    'precipType': 'rain',
    'temperature': 72.44,
    'apparentTemperature': 72.44,
    'dewPoint': 56.22,
    'humidity': 0.57,
    'pressure': 1003.89,
    'windSpeed': 7.73,
    'windGust': 11.77,
    'windBearing': 33,
    'cloudCover': 0.19,
    'uvIndex': 0,
    'visibility': 6.75,
    'ozone': 344.7},
   {'time': 1558288800,
    'summary': 'Clear',
    'icon': 'clear-day',
    'precipIntensity': 0.0085,
    'precipProbability': 0.05,
    'precipType': 'rain',
    'temperature': 70.28,
    'apparentTemperature': 70.28,
    'dewPoint': 58.93,
    'humidity': 0.67,
    'pressure': 1003.99,
    'windSpeed': 7.04,
    'windGust': 14.51,
    'windBearing': 33,
    'cloudCover': 0.19,
    'uvIndex': 0,
    'visibility': 6.42,
    'ozone': 348.07},
   {'time': 1558292400,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0.0077,
    'precipProbability': 0.05,
    'precipType': 'rain',
    'temperature': 68.42,
    'apparentTemperature': 68.42,
    'dewPoint': 59.5,
    'humidity': 0.73,
    'pressure': 1004.13,
    'windSpeed': 7.29,
    'windGust': 14.46,
    'windBearing': 48,
    'cloudCover': 0.27,
    'uvIndex': 0,
    'visibility': 6.89,
    'ozone': 347.71},
   {'time': 1558296000,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0.0049,
    'precipProbability': 0.05,
    'precipType': 'rain',
    'temperature': 67.15,
    'apparentTemperature': 67.15,
    'dewPoint': 58.64,
    'humidity': 0.74,
    'pressure': 1004.33,
    'windSpeed': 6.37,
    'windGust': 13.8,
    'windBearing': 40,
    'cloudCover': 0.27,
    'uvIndex': 0,
    'visibility': 7.51,
    'ozone': 346.5},
   {'time': 1558299600,
    'summary': 'Partly Cloudy',
    'icon': 'partly-cloudy-night',
    'precipIntensity': 0.0028,
    'precipProbability': 0.04,
    'precipType': 'rain',
    'temperature': 65.63,
    'apparentTemperature': 65.63,
    'dewPoint': 58.36,
    'humidity': 0.77,
    'pressure': 1004.44,
    'windSpeed': 5.85,
    'windGust': 12.82,
    'windBearing': 43,
    'cloudCover': 0.35,
    'uvIndex': 0,
    'visibility': 7.99,
    'ozone': 344.94}]},
 'daily': {'data': [{'time': 1558216800,
    'summary': 'Mostly cloudy in the morning.',
    'icon': 'partly-cloudy-day',
    'sunriseTime': 1558235226,
    'sunsetTime': 1558292615,
    'moonPhase': 0.53,
    'precipIntensity': 0.0014,
    'precipIntensityMax': 0.0085,
    'precipIntensityMaxTime': 1558288800,
    'precipProbability': 0.24,
    'precipType': 'rain',
    'temperatureHigh': 77.06,
    'temperatureHighTime': 1558270800,
    'temperatureLow': 57.82,
    'temperatureLowTime': 1558324800,
    'apparentTemperatureHigh': 77.06,
    'apparentTemperatureHighTime': 1558270800,
    'apparentTemperatureLow': 57.82,
    'apparentTemperatureLowTime': 1558324800,
    'dewPoint': 52.01,
    'humidity': 0.64,
    'pressure': 1005.67,
    'windSpeed': 6.48,
    'windGust': 24.49,
    'windGustTime': 1558278000,
    'windBearing': 73,
    'cloudCover': 0.39,
    'uvIndex': 6,
    'uvIndexTime': 1558260000,
    'visibility': 6.43,
    'ozone': 343.45,
    'temperatureMin': 52.15,
    'temperatureMinTime': 1558227600,
    'temperatureMax': 77.06,
    'temperatureMaxTime': 1558270800,
    'apparentTemperatureMin': 52.15,
    'apparentTemperatureMinTime': 1558227600,
    'apparentTemperatureMax': 77.06,
    'apparentTemperatureMaxTime': 1558270800}]},
 'flags': {'sources': ['cmc', 'gfs', 'icon', 'isd', 'madis'],
  'nearest-station': 7.072,
  'units': 'us'},
 'offset': 2}

In [58]:
precip = []
for x in df_dummy['Date']:
    precip.append(get_weather_data_given_date(x)['currently']['icon'])

In [59]:
precip

['rain',
 'partly-cloudy-day',
 'partly-cloudy-day',
 'partly-cloudy-day',
 'partly-cloudy-day',
 'rain',
 'partly-cloudy-day',
 'partly-cloudy-day',
 'rain',
 'clear-day']

In [64]:
rained = []
for x in precip:
    if x == 'rain':
        rained.append("True")
    else:
        rained.append("False")
rained

['True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False']

In [75]:
df_dummy

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,rained
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,True
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,False
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,False
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,False
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,False
5,1097,D1,2011,2012-01-20,M'gladbach,Bayern Munich,3,1,H,True
6,1098,D1,2011,2012-02-04,Hamburg,Bayern Munich,1,1,D,False
7,1099,D1,2011,2012-04-21,Werder Bremen,Bayern Munich,1,2,A,False
8,1100,D1,2011,2011-09-18,Schalke 04,Bayern Munich,0,2,A,True
9,1101,D1,2011,2011-10-23,Hannover,Bayern Munich,2,1,H,False

In [79]:
df_dummy.groupby('HomeTeam').sum()

               Match_ID  Season  FTHG  FTAG
HomeTeam
Freiburg           1096    2011     0     0
Hamburg            1098    2011     1     1
Hannover           1101    2011     2     1
M'gladbach         1097    2011     3     1
Mainz              1095    2011     3     2
Nurnberg           1092    2011     0     1
Schalke 04         1100    2011     0     2
Stuttgart          1093    2011     1     2
Werder Bremen      1099    2011     1     2
Wolfsburg          1094    2011     0     1

In [80]:
df_dummy.groupby('AwayTeam').sum()

               Match_ID  Season  FTHG  FTAG
AwayTeam
Bayern Munich     10965   20110    11    13

In [92]:
home_win = []
away_win = []
for outcome in df_dummy['FTR']:
    if outcome == 'A':
        home_win.append(0)
        away_win.append(1)
    elif outcome == 'H':
        home_win.append(1)
        away_win.append(0)
    else:
        home_win.append(0)
        away_win.append(0)

In [93]:
home_win

[0, 0, 0, 1, 0, 1, 0, 0, 0, 1]

In [94]:
away_win

[1, 1, 1, 0, 0, 0, 0, 1, 1, 0]

In [95]:
df_dummy['home_win'] = home_win
df_dummy['away_win'] = away_win

In [96]:
df_dummy

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,rained,home_win,away_win
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,True,0,1
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,False,0,1
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,False,0,1
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,False,1,0
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,False,0,0
5,1097,D1,2011,2012-01-20,M'gladbach,Bayern Munich,3,1,H,True,1,0
6,1098,D1,2011,2012-02-04,Hamburg,Bayern Munich,1,1,D,False,0,0
7,1099,D1,2011,2012-04-21,Werder Bremen,Bayern Munich,1,2,A,False,0,1
8,1100,D1,2011,2011-09-18,Schalke 04,Bayern Munich,0,2,A,True,0,1
9,1101,D1,2011,2011-10-23,Hannover,Bayern Munich,2,1,H,False,1,0

In [97]:
df_dummy.groupby('HomeTeam')['home_win'].sum()

HomeTeam
Freiburg         0
Hamburg          0
Hannover         1
M'gladbach       1
Mainz            1
Nurnberg         0
Schalke 04       0
Stuttgart        0
Werder Bremen    0
Wolfsburg        0
Name: home_win, dtype: int64

In [98]:
home_loss = []
away_loss = []
for outcome in df_dummy['FTR']:
    if outcome == 'A':
        home_loss.append(1)
        away_loss.append(0)
    elif outcome == 'H':
        home_loss.append(0)
        away_loss.append(1)
    else:
        home_loss.append(0)
        away_loss.append(0)

In [99]:
df_dummy['home_loss'] = home_loss
df_dummy['away_loss'] = away_loss

In [100]:
df_dummy

,Match_ID,Div,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,rained,home_win,away_win,home_loss,away_loss
0,1092,D1,2011,2012-03-31,Nurnberg,Bayern Munich,0,1,A,True,0,1,1,0
1,1093,D1,2011,2011-12-11,Stuttgart,Bayern Munich,1,2,A,False,0,1,1,0
2,1094,D1,2011,2011-08-13,Wolfsburg,Bayern Munich,0,1,A,False,0,1,1,0
3,1095,D1,2011,2011-11-27,Mainz,Bayern Munich,3,2,H,False,1,0,0,1
4,1096,D1,2011,2012-02-18,Freiburg,Bayern Munich,0,0,D,False,0,0,0,0
5,1097,D1,2011,2012-01-20,M'gladbach,Bayern Munich,3,1,H,True,1,0,0,1
6,1098,D1,2011,2012-02-04,Hamburg,Bayern Munich,1,1,D,False,0,0,0,0
7,1099,D1,2011,2012-04-21,Werder Bremen,Bayern Munich,1,2,A,False,0,1,1,0
8,1100,D1,2011,2011-09-18,Schalke 04,Bayern Munich,0,2,A,True,0,1,1,0
9,1101,D1,2011,2011-10-23,Hannover,Bayern Munich,2,1,H,False,1,0,0,1

In [101]:
df_dummy.groupby('HomeTeam')['home_win', 'home_loss'].sum()

               home_win  home_loss
HomeTeam
Freiburg              0          0
Hamburg               0          0
Hannover              1          0
M'gladbach            1          0
Mainz                 1          0
Nurnberg              0          1
Schalke 04            0          1
Stuttgart             0          1
Werder Bremen         0          1
Wolfsburg             0          1

In [102]:
df_dummy.groupby('AwayTeam')['away_win', 'away_loss'].sum()

               away_win  away_loss
AwayTeam
Bayern Munich         5          3